version: "3"

services:
  tftp_server:
    tty: true
    build: .
    container_name: tftp_server
    ports:
      - 69:69/udp
    volumes:
      - ./tftp_dir:/srv/tftp
      # TFTPユーザ
    # privileged: true
    restart: always